### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by mikoreal** [bnjones/contourtool#2]
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "contourtool\__main__.py", line 10, in <module>
    from . import main
ImportError: attempted relative import with no known parent package

**Comment by mikoreal** [comment]
Not an issue with the actual program but python prerequisites.
