### ISSUE TITLE
Module not found when running contourtool -o

### ISSUE THREAD

**Issue by drventure** [bnjones/contourtool#7]
I think i've got this installed right, no errors during the "python setup.py install"
When I run "contourtool -o x.csv"

I get a module not found

Traceback (most recent call last):
  File "C:\Python38\Scripts\contourtool-script.py", line 11, in <module>
    load_entry_point('contourtool==0.1', 'console_scripts', 'contourtool')()
  File "C:\Python38\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python38\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "C:\Python38\lib\site-packages\pkg_resources\__init__.py", line 2462, in load
    return self.resolve()
  File "C:\Python38\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Python38\lib\site-packages\contourtool-0.1-py3.8.egg\contourtool\__init__.py", line 26, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Python38\lib\site-packages\contourtool-0.1-py3.8.egg\contourtool\astm.py", line 12, in <module>
ModuleNotFoundError: No module named 'controlchars'

I've checked the egg file and the contourtool folder and that "controlchars.py" file is there.

Any ideas?

**Comment by drventure** [comment]
forgot to mention, running python 38 on windows 10. Not sure if that would make a difference.
